// Tests for card-expense budget sync (src/core/card-expenses.js)
//
// Card-charged costs never touch the cash pool — they are autopaid by a
// credit card. This sync mirrors them into the spending budgets so they
// still count against a monthly spending limit. Every card charge due this
// month is logged up front (with its real charge date) — the budget shows
// committed card spending from day one, not just charges already posted.
//
// Run with: node --test tests/card-expenses.test.js

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import {
    findBudgetForCost,
    syncCardExpenses,
    computeCardPayoffStatus,
    cardChargesByDebt,
    cashExpensesForMonth,
    CARD_AUTOPAY_BUDGET_ID,
    CARD_AUTOPAY_BUDGET_NAME,
    CATEGORY_BUDGETS,
} from './helpers.js';

const MONTH = '2026-8'; // September 2026 (0-indexed month)

function cardCost(overrides = {}) {
    return {
        id: 'c1',
        name: 'Netflix',
        amount: 15,
        dueDay: 10,
        category: 'subscription',
        paymentMethod: 'card',
        intervalMonths: 1,
        ...overrides,
    };
}

function budget(overrides = {}) {
    return { id: 'b1', name: 'Subscriptions', amount: 100, expenses: [], ...overrides };
}

function sync(overrides = {}) {
    return syncCardExpenses({
        recurringCosts: [],
        oneTimeCosts: [],
        spendingBudgets: [],
        monthKey: MONTH,
        skips: [],
        ...overrides,
    });
}

describe('findBudgetForCost', () => {

    test('explicit budgetId wins over everything', () => {
        const budgets = [
            { id: 'b1', name: 'Subscriptions' },
            { id: 'b2', name: 'Fun Money' },
        ];
        const cost = cardCost({ budgetId: 'b2', name: 'Subscriptions Galore' });
        assert.equal(findBudgetForCost(cost, budgets).id, 'b2');
    });

    test('missing budgetId falls through to name matching', () => {
        const budgets = [{ id: 'b1', name: 'Netflix' }];
        const cost = cardCost({ budgetId: 'gone', name: 'Netflix' });
        assert.equal(findBudgetForCost(cost, budgets).id, 'b1');
    });

    test('matches budget by cost name (case/emoji-insensitive)', () => {
        const budgets = [{ id: 'b1', name: '📱 Netflix 🎬' }];
        assert.equal(findBudgetForCost(cardCost(), budgets).id, 'b1');
    });

    test('matches budget by category keyword', () => {
        const budgets = [{ id: 'b1', name: 'Subscriptions' }];
        assert.equal(findBudgetForCost(cardCost({ name: 'ZZZ Prime' }), budgets).id, 'b1');
    });

    test('utility category matches utilities budget', () => {
        const budgets = [{ id: 'b1', name: 'Utilities' }];
        assert.equal(findBudgetForCost(cardCost({ category: 'utility', name: 'Frontier' }), budgets).id, 'b1');
    });

    test('returns null when nothing matches', () => {
        const budgets = [{ id: 'b1', name: 'Groceries' }];
        assert.equal(findBudgetForCost(cardCost({ name: 'Netflix' }), budgets), null);
    });
});

describe('syncCardExpenses', () => {

    test('logs card cost into a name/category-matched budget, with its charge date', () => {
        const { budgets, changed } = sync({
            recurringCosts: [cardCost()],
            spendingBudgets: [budget()],
        });
        assert.equal(changed, true);
        const exp = budgets[0].expenses;
        assert.equal(exp.length, 1);
        assert.equal(exp[0].description, 'Netflix');
        assert.equal(exp[0].amount, 15);
        assert.equal(exp[0].date, '2026-09-10');
        assert.equal(exp[0].autoCard, true);
        assert.equal(exp[0].costId, 'c1');
    });

    test('logs card costs before their due day — committed spending is visible up front', () => {
        // Regression: card expenses used to appear only once dueDay <= today,
        // so the budget understated committed card spending for most of the month.
        const { budgets, changed } = sync({
            recurringCosts: [cardCost({ dueDay: 28 })],
            spendingBudgets: [budget()],
        });
        assert.equal(changed, true);
        assert.equal(budgets[0].expenses.length, 1);
        assert.equal(budgets[0].expenses[0].date, '2026-09-28');
    });

    test('unmatched card cost creates a category budget (not the fallback)', () => {
        const { budgets, changed } = sync({
            recurringCosts: [cardCost()], // subscription 'Netflix'
            spendingBudgets: [{ id: 'b1', name: 'Groceries', amount: 400, expenses: [] }],
        });
        assert.equal(changed, true);
        const cat = budgets.find(b => b.id === CATEGORY_BUDGETS.subscription.id);
        assert.ok(cat);
        assert.equal(cat.name, CATEGORY_BUDGETS.subscription.name);
        assert.equal(cat.autoGenerated, true);
        assert.equal(cat.expenses.length, 1);
        assert.equal(cat.expenses[0].costId, 'c1');
        assert.equal(cat.exception.month, MONTH);
        assert.equal(cat.exception.amount, 15); // limit tracks routed total
        // 'other'/'one-time' are the only things that hit the catch-all now
        assert.equal(budgets.find(b => b.id === CARD_AUTOPAY_BUDGET_ID), undefined);
    });

    test('utility and maintenance costs create their own category budgets', () => {
        const { budgets } = sync({
            recurringCosts: [
                cardCost({ id: 'c1', category: 'utility', name: 'Electric' }),
                cardCost({ id: 'c2', category: 'maintenance', name: 'Oil change', amount: 60 }),
            ],
        });
        const util = budgets.find(b => b.id === CATEGORY_BUDGETS.utility.id);
        const maint = budgets.find(b => b.id === CATEGORY_BUDGETS.maintenance.id);
        assert.ok(util && maint);
        assert.equal(util.expenses[0].costId, 'c1');
        assert.equal(maint.expenses[0].costId, 'c2');
        assert.equal(util.exception.amount, 15);
        assert.equal(maint.exception.amount, 60);
    });

    test('category budget limit sums all charges routed to it', () => {
        const { budgets } = sync({
            recurringCosts: [
                cardCost({ id: 'c1', dueDay: 1 }),
                cardCost({ id: 'c2', name: 'Hulu', amount: 20, dueDay: 30 }),
            ],
        });
        const cat = budgets.find(b => b.id === CATEGORY_BUDGETS.subscription.id);
        assert.equal(cat.exception.amount, 35); // 15 + 20
        assert.equal(cat.expenses.length, 2);   // both logged up front
    });

    test("'other' and 'one-time' categories still use the Card Autopay fallback", () => {
        const { budgets } = sync({
            recurringCosts: [cardCost({ id: 'c1', category: 'other', name: 'Random charge' })],
            oneTimeCosts:  [cardCost({ id: 'c2', category: 'one-time', addedMonth: MONTH, name: 'Repair', amount: 40 })],
        });
        const auto = budgets.find(b => b.id === CARD_AUTOPAY_BUDGET_ID);
        assert.ok(auto);
        assert.equal(auto.expenses.length, 2);
        assert.equal(auto.exception.amount, 55); // 15 + 40
    });

    test('category budget is removed once nothing routes to it (no manual expenses)', () => {
        const first = sync({ recurringCosts: [cardCost()] });
        const cat = first.budgets.find(b => b.id === CATEGORY_BUDGETS.subscription.id);
        assert.ok(cat);
        const second = sync({ recurringCosts: [], spendingBudgets: first.budgets });
        assert.equal(second.budgets.find(b => b.id === CATEGORY_BUDGETS.subscription.id), undefined);
    });

    test('category budget survives with manual expenses even when nothing routes', () => {
        const first = sync({ recurringCosts: [cardCost()] });
        const cat = first.budgets.find(b => b.id === CATEGORY_BUDGETS.subscription.id);
        cat.expenses.push({ id: 'e1', description: 'Manual', amount: 10 });
        const second = sync({ recurringCosts: [], spendingBudgets: first.budgets });
        const kept = second.budgets.find(b => b.id === CATEGORY_BUDGETS.subscription.id);
        assert.ok(kept);
        assert.ok(kept.expenses.some(e => e.id === 'e1'));
    });

    test("budgetCategory routes an 'other' cost to its category budget (user-taught)", () => {
        const { budgets } = sync({
            recurringCosts: [cardCost({ category: 'other', name: 'Weird service', budgetCategory: 'subscription' })],
        });
        const cat = budgets.find(b => b.id === CATEGORY_BUDGETS.subscription.id);
        assert.ok(cat);
        assert.equal(cat.expenses[0].costId, 'c1');
        assert.equal(budgets.find(b => b.id === CARD_AUTOPAY_BUDGET_ID), undefined);
    });

    test("budgetCategory 'autopay' explicitly keeps a cost in the fallback", () => {
        const { budgets, newFallbackCosts } = sync({
            recurringCosts: [cardCost({ category: 'subscription', budgetCategory: 'autopay' })],
        });
        const auto = budgets.find(b => b.id === CARD_AUTOPAY_BUDGET_ID);
        assert.ok(auto);
        assert.equal(auto.expenses.length, 1);
        // Explicitly-kept costs must NOT trigger the categorize prompt
        assert.equal(newFallbackCosts.length, 0);
    });

    test('newFallbackCosts reports only newly-landed unclassified costs', () => {
        const costs = [
            cardCost({ id: 'c1', category: 'other', name: 'Random' }),
            cardCost({ id: 'c2', category: 'other', name: 'Also random', budgetCategory: 'autopay' }),
        ];
        const first = sync({ recurringCosts: costs });
        assert.deepEqual(first.newFallbackCosts.map(c => c.id), ['c1']);
        // Second sync: expense already exists — not "newly landed" anymore
        const second = sync({ recurringCosts: costs, spendingBudgets: first.budgets });
        assert.equal(second.newFallbackCosts.length, 0);
    });

    test('migration: expenses parked in the fallback move to the category budget', () => {
        // Legacy state: a subscription auto expense lives in Card Autopay
        // (pre-category routing). Sync should relocate it and drop the
        // now-empty fallback.
        const legacy = [{
            id: CARD_AUTOPAY_BUDGET_ID, name: CARD_AUTOPAY_BUDGET_NAME,
            amount: 15, autoGenerated: true,
            exception: { month: MONTH, amount: 15, auto: true },
            expenses: [{ id: 'cardauto_c1', description: 'Netflix', amount: 15, date: '2026-09-10', costId: 'c1', autoCard: true }],
        }];
        const { budgets } = sync({ recurringCosts: [cardCost()], spendingBudgets: legacy });
        const cat = budgets.find(b => b.id === CATEGORY_BUDGETS.subscription.id);
        assert.ok(cat);
        assert.equal(cat.expenses.length, 1);
        assert.equal(cat.expenses[0].id, 'cardauto_c1');
        // Fallback had nothing else → removed
        assert.equal(budgets.find(b => b.id === CARD_AUTOPAY_BUDGET_ID), undefined);
    });

    test('respects a user-set (non-auto) exception on the auto budget', () => {
        const auto = {
            id: CARD_AUTOPAY_BUDGET_ID, name: CARD_AUTOPAY_BUDGET_NAME,
            amount: 50, autoGenerated: true, expenses: [],
            exception: { month: MONTH, amount: 999 }, // user override — no auto flag
        };
        const { budgets } = sync({ recurringCosts: [cardCost()], spendingBudgets: [auto] });
        assert.equal(budgets[0].exception.amount, 999);
    });

    test('is idempotent — second sync reports no changes', () => {
        const first = sync({ recurringCosts: [cardCost()], spendingBudgets: [budget()] });
        const second = sync({ recurringCosts: [cardCost()], spendingBudgets: first.budgets });
        assert.equal(second.changed, false);
    });

    test('ignores direct-payment costs entirely', () => {
        const { budgets, changed } = sync({
            recurringCosts: [cardCost({ paymentMethod: 'direct' })],
            spendingBudgets: [budget()],
        });
        assert.equal(changed, false);
        assert.equal(budgets[0].expenses.length, 0);
    });

    test('syncs one-time card costs too', () => {
        const { budgets } = sync({
            oneTimeCosts: [cardCost({ category: 'one-time', addedMonth: MONTH, dueDay: 5 })],
            spendingBudgets: [budget()],
        });
        // 'one-time' has no category keyword — lands in the fallback budget
        const auto = budgets.find(b => b.id === CARD_AUTOPAY_BUDGET_ID);
        assert.equal(auto.expenses.length, 1);
        assert.equal(auto.expenses[0].costId, 'c1');
    });

    test('does not sync interval costs that are not due this month', () => {
        const { budgets, changed } = sync({
            recurringCosts: [cardCost({ intervalMonths: 12, nextDueMonth: '2027-2' })],
            spendingBudgets: [budget()],
        });
        assert.equal(changed, false);
        assert.equal(budgets[0].expenses.length, 0);
    });

    test('removes auto expense when its cost is deleted', () => {
        const first = sync({ recurringCosts: [cardCost()], spendingBudgets: [budget()] });
        const second = sync({ recurringCosts: [], spendingBudgets: first.budgets });
        assert.equal(second.changed, true);
        assert.equal(second.budgets[0].expenses.length, 0);
    });

    test('removes auto expense when cost switches to direct pay', () => {
        const first = sync({ recurringCosts: [cardCost()], spendingBudgets: [budget()] });
        const second = sync({
            recurringCosts: [cardCost({ paymentMethod: 'direct' })],
            spendingBudgets: first.budgets,
        });
        assert.equal(second.budgets[0].expenses.length, 0);
    });

    test('moves auto expense when the cost is reassigned to another budget', () => {
        const b1 = budget();
        const b2 = { id: 'b2', name: 'Fun Money', amount: 50, expenses: [] };
        const first = sync({ recurringCosts: [cardCost()], spendingBudgets: [b1, b2] });
        const second = sync({
            recurringCosts: [cardCost({ budgetId: 'b2' })],
            spendingBudgets: first.budgets,
        });
        const sb = second.budgets.find(b => b.id === 'b1');
        const fm = second.budgets.find(b => b.id === 'b2');
        assert.equal(sb.expenses.length, 0);
        assert.equal(fm.expenses.length, 1);
    });

    test('mirrors updated name/amount on the auto expense', () => {
        const first = sync({ recurringCosts: [cardCost()], spendingBudgets: [budget()] });
        const second = sync({
            recurringCosts: [cardCost({ name: 'Netflix Premium', amount: 22 })],
            spendingBudgets: first.budgets,
        });
        assert.equal(second.budgets[0].expenses[0].description, 'Netflix Premium');
        assert.equal(second.budgets[0].expenses[0].amount, 22);
    });

    test('tombstoned costs are not re-added', () => {
        const { budgets, changed } = sync({
            recurringCosts: [cardCost()],
            spendingBudgets: [budget()],
            skips: [`${MONTH}:c1`],
        });
        assert.equal(changed, false);
        assert.equal(budgets[0].expenses.length, 0);
    });

    test('leaves manual expenses untouched', () => {
        const b = budget({ expenses: [{ id: 'e1', description: 'Movies', amount: 30, date: '2026-09-03' }] });
        const { budgets } = sync({ recurringCosts: [cardCost()], spendingBudgets: [b] });
        assert.equal(budgets[0].expenses.length, 2);
        assert.ok(budgets[0].expenses.some(e => e.id === 'e1'));
    });

    test('clamps expense date to the last day of short months', () => {
        const { budgets } = sync({
            recurringCosts: [cardCost({ dueDay: 31 })],
            spendingBudgets: [budget()],
            monthKey: '2026-1', // February 2026 — 28 days
        });
        assert.equal(budgets[0].expenses[0].date, '2026-02-28');
    });
});

describe('computeCardPayoffStatus', () => {

    const income = (amount) => [{ id: 'i1', label: 'Paycheck', amount, date: '2026-09-01', scheduleType: 'monthly' }];
    const debt   = (minPayment) => [{ id: 'd1', name: 'Visa', balance: 5000, minPayment }];

    test('sustainable when income covers card charges after direct costs and minimums', () => {
        const s = computeCardPayoffStatus({
            recurringCosts: [
                cardCost(), // $15 card
                cardCost({ id: 'c2', name: 'Rent', amount: 1000, paymentMethod: 'direct' }),
            ],
            incomeEntries: income(2000),
            debts: debt(200),
            monthKey: MONTH,
        });
        // cashAvailable = 2000 - 1000 - 200 = 800; card charges 15 <= 800
        assert.equal(s.cardCharges, 15);
        assert.equal(s.cashAvailable, 800);
        assert.equal(s.sustainable, true);
        assert.equal(s.shortfall, 0);
    });

    test('unsustainable when card charges exceed available cash', () => {
        const s = computeCardPayoffStatus({
            recurringCosts: [
                cardCost({ amount: 900 }),
                cardCost({ id: 'c2', name: 'Rent', amount: 1000, paymentMethod: 'direct' }),
            ],
            incomeEntries: income(2000),
            debts: debt(200),
            monthKey: MONTH,
        });
        // 2000 - 1000 - 200 = 800 available; $900 charged → $100 short
        assert.equal(s.cardCharges, 900);
        assert.equal(s.cashAvailable, 800);
        assert.equal(s.sustainable, false);
        assert.equal(s.shortfall, 100);
    });

    test('no card charges is trivially sustainable', () => {
        const s = computeCardPayoffStatus({
            recurringCosts: [cardCost({ paymentMethod: 'direct' })],
            incomeEntries: income(2000),
            monthKey: MONTH,
        });
        assert.equal(s.cardCharges, 0);
        assert.equal(s.sustainable, true);
    });

    test('counts one-time card costs in the month total', () => {
        const s = computeCardPayoffStatus({
            oneTimeCosts: [cardCost({ category: 'one-time', addedMonth: MONTH, amount: 60 })],
            incomeEntries: income(2000),
            monthKey: MONTH,
        });
        assert.equal(s.cardCharges, 60);
    });

    test('one-time card costs also reduce what is available when paid direct', () => {
        const s = computeCardPayoffStatus({
            oneTimeCosts: [cardCost({ category: 'one-time', addedMonth: MONTH, amount: 500, paymentMethod: 'direct' })],
            incomeEntries: income(2000),
            debts: debt(200),
            monthKey: MONTH,
        });
        assert.equal(s.cashAvailable, 2000 - 500 - 200);
    });

    test('min-pay overrides affect available cash', () => {
        const s = computeCardPayoffStatus({
            incomeEntries: income(2000),
            debts: debt(200),
            minPayOverrides: { d1: 700 },
            monthKey: MONTH,
        });
        assert.equal(s.cashAvailable, 1300);
    });

    test('debts with zero balance do not consume cash', () => {
        const s = computeCardPayoffStatus({
            incomeEntries: income(2000),
            debts: [{ id: 'd1', name: 'Visa', balance: 0, minPayment: 200 }],
            monthKey: MONTH,
        });
        assert.equal(s.cashAvailable, 2000);
    });

    test('per-card breakdown groups charges by linked debt', () => {
        const s = computeCardPayoffStatus({
            recurringCosts: [
                cardCost({ id: 'c1', amount: 10, cardDebtId: 'd1' }),
                cardCost({ id: 'c2', amount: 20, cardDebtId: 'd1' }),
                cardCost({ id: 'c3', amount: 30, cardDebtId: 'd2' }),
                cardCost({ id: 'c4', amount: 40 }), // unlinked
                cardCost({ id: 'c5', amount: 50, paymentMethod: 'direct' }),
            ],
            incomeEntries: income(2000),
            monthKey: MONTH,
        });
        assert.equal(s.byDebt.d1, 30);
        assert.equal(s.byDebt.d2, 30);
        assert.equal(s.unassigned, 40);
        assert.equal(s.cardCharges, 100);
    });
});

describe('cardChargesByDebt', () => {

    test('returns per-debt totals and unassigned remainder', () => {
        const r = cardChargesByDebt({
            recurringCosts: [
                cardCost({ id: 'c1', amount: 10, cardDebtId: 'd1' }),
                cardCost({ id: 'c2', amount: 5 }),
            ],
            monthKey: MONTH,
        });
        assert.deepEqual(r.byDebt, { d1: 10 });
        assert.equal(r.unassigned, 5);
    });

    test('excludes card costs not due this month', () => {
        const r = cardChargesByDebt({
            recurringCosts: [
                cardCost({ id: 'c1', amount: 10, cardDebtId: 'd1', intervalMonths: 12, nextDueMonth: '2027-0' }),
            ],
            monthKey: MONTH,
        });
        assert.deepEqual(r.byDebt, {});
        assert.equal(r.unassigned, 0);
    });

    test('manual card expenses count toward their linked card', () => {
        const r = cardChargesByDebt({
            spendingBudgets: [{
                id: 'b1', name: 'Fun',
                expenses: [
                    { id: 'e1', description: 'Concert', amount: 60, date: '2026-09-12', paymentMethod: 'card', cardDebtId: 'd1' },
                    { id: 'e2', description: 'Card, no link', amount: 20, date: '2026-09-15', paymentMethod: 'card' },
                    { id: 'e3', description: 'Cash purchase', amount: 30, date: '2026-09-15' }, // direct — ignored
                ],
            }],
            monthKey: MONTH,
        });
        assert.deepEqual(r.byDebt, { d1: 60 });
        assert.equal(r.unassigned, 20);
    });

    test('manual card expenses respect month boundaries like cash expenses', () => {
        const r = cardChargesByDebt({
            spendingBudgets: [{
                id: 'b1', name: 'Fun',
                expenses: [
                    { id: 'e1', description: 'In month', amount: 60, date: '2026-09-12', paymentMethod: 'card', cardDebtId: 'd1' },
                    { id: 'e2', description: 'Last month', amount: 20, date: '2026-08-12', paymentMethod: 'card', cardDebtId: 'd1' },
                    { id: 'e3', description: 'Undated', amount: 10, paymentMethod: 'card', cardDebtId: 'd1' },
                    { id: 'e4', description: 'Auto mirror', amount: 99, autoCard: true, paymentMethod: 'card', cardDebtId: 'd1' }, // autoCard exempt — bills carry it
                ],
            }],
            monthKey: MONTH,
        });
        assert.equal(r.byDebt.d1, 70); // 60 + undated 10; excludes Aug + autoCard
    });

    test('manual card expenses flow into payoff sustainability', () => {
        const s = computeCardPayoffStatus({
            incomeEntries: [{ id: 'i1', amount: 1000 }],
            spendingBudgets: [{ id: 'b1', name: 'X', expenses: [
                { id: 'e1', description: 'Card buy', amount: 400, date: '2026-09-10', paymentMethod: 'card', cardDebtId: 'd1' },
            ]}],
            monthKey: MONTH,
        });
        assert.equal(s.cardCharges, 400);
        assert.equal(s.byDebt.d1, 400);
    });
});

describe('cashExpensesForMonth', () => {

    test('flattens manual expenses with their budget name', () => {
        const budgets = [
            { id: 'b1', name: 'Groceries', expenses: [{ id: 'e1', description: 'Walmart', amount: 80, date: '2026-09-05' }] },
            { id: 'b2', name: 'Fun',       expenses: [{ id: 'e2', description: 'Marketplace', amount: 120, date: '2026-09-12' }] },
        ];
        const out = cashExpensesForMonth(budgets, MONTH);
        assert.equal(out.length, 2);
        assert.equal(out.find(e => e.id === 'e2').budgetName, 'Fun');
    });

    test('excludes auto card expenses — they are not cash', () => {
        const budgets = [{
            id: 'b1', name: 'Subs',
            expenses: [
                { id: 'e1', description: 'Manual', amount: 10, date: '2026-09-01' },
                { id: 'cardauto_c1', description: 'Netflix', amount: 15, date: '2026-09-10', autoCard: true, costId: 'c1' },
            ],
        }];
        const out = cashExpensesForMonth(budgets, MONTH);
        assert.equal(out.length, 1);
        assert.equal(out[0].id, 'e1');
    });

    test('excludes expenses dated outside the working month', () => {
        const budgets = [{
            id: 'b1', name: 'Misc',
            expenses: [
                { id: 'e1', description: 'This month', amount: 10, date: '2026-09-01' },
                { id: 'e2', description: 'Backdated to August', amount: 20, date: '2026-08-30' },
            ],
        }];
        const out = cashExpensesForMonth(budgets, MONTH);
        assert.equal(out.length, 1);
        assert.equal(out[0].id, 'e1');
    });

    test('includes undated expenses', () => {
        const budgets = [{ id: 'b1', name: 'Misc', expenses: [{ id: 'e1', description: 'Cash', amount: 5 }] }];
        assert.equal(cashExpensesForMonth(budgets, MONTH).length, 1);
    });

    test('excludes manual card-paid expenses — they land on the card, not cash', () => {
        const budgets = [{
            id: 'b1', name: 'Misc',
            expenses: [
                { id: 'e1', description: 'Debit purchase', amount: 10, date: '2026-09-01' },
                { id: 'e2', description: 'Credit purchase', amount: 50, date: '2026-09-02', paymentMethod: 'card', cardDebtId: 'd1' },
            ],
        }];
        const out = cashExpensesForMonth(budgets, MONTH);
        assert.equal(out.length, 1);
        assert.equal(out[0].id, 'e1');
    });

    test('handles missing budgets/expenses gracefully', () => {
        assert.deepEqual(cashExpensesForMonth([], MONTH), []);
        assert.deepEqual(cashExpensesForMonth(undefined, MONTH), []);
        assert.deepEqual(cashExpensesForMonth([{ id: 'b1', name: 'X' }], MONTH), []);
    });
});

    test('items lists every contributing charge with its card and source', () => {
        const r = cardChargesByDebt({
            recurringCosts: [
                cardCost({ id: 'c1', name: 'Netflix', amount: 15, cardDebtId: 'd1' }),
            ],
            spendingBudgets: [{
                id: 'b1', name: 'Fun',
                expenses: [
                    { id: 'e1', description: 'Concert', amount: 60, date: '2026-09-12', paymentMethod: 'card' },
                    { id: 'e2', description: 'Auto mirror', amount: 15, autoCard: true, costId: 'c1' }, // counted via cost side — skipped here
                ],
            }],
            monthKey: MONTH,
        });
        assert.deepEqual(r.items, [
            { name: 'Netflix', amount: 15, debtId: 'd1', source: 'bill' },
            { name: 'Concert', amount: 60, debtId: null, source: 'expense' },
        ]);
    });
